// Data provinsi dan kabupaten/kota Indonesia untuk validasi NIK

export interface Province {
  code: string;
  name: string;
}

export interface City {
  code: string;
  name: string;
  provinceCode: string;
}

export const provinces: Province[] = [
  { code: "11", name: "Aceh" },
  { code: "12", name: "Sumatera Utara" },
  { code: "13", name: "Sumatera Barat" },
  { code: "14", name: "Riau" },
  { code: "15", name: "Jambi" },
  { code: "16", name: "Sumatera Selatan" },
  { code: "17", name: "Bengkulu" },
  { code: "18", name: "Lampung" },
  { code: "19", name: "Kepulauan Bangka Belitung" },
  { code: "21", name: "Kepulauan Riau" },
  { code: "31", name: "DKI Jakarta" },
  { code: "32", name: "Jawa Barat" },
  { code: "33", name: "Jawa Tengah" },
  { code: "34", name: "DI Yogyakarta" },
  { code: "35", name: "Jawa Timur" },
  { code: "36", name: "Banten" },
  { code: "51", name: "Bali" },
  { code: "52", name: "Nusa Tenggara Barat" },
  { code: "53", name: "Nusa Tenggara Timur" },
  { code: "61", name: "Kalimantan Barat" },
  { code: "62", name: "Kalimantan Tengah" },
  { code: "63", name: "Kalimantan Selatan" },
  { code: "64", name: "Kalimantan Timur" },
  { code: "65", name: "Kalimantan Utara" },
  { code: "71", name: "Sulawesi Utara" },
  { code: "72", name: "Sulawesi Tengah" },
  { code: "73", name: "Sulawesi Selatan" },
  { code: "74", name: "Sulawesi Tenggara" },
  { code: "75", name: "Gorontalo" },
  { code: "76", name: "Sulawesi Barat" },
  { code: "81", name: "Maluku" },
  { code: "82", name: "Maluku Utara" },
  { code: "91", name: "Papua Barat" },
  { code: "92", name: "Papua Barat Daya" },
  { code: "93", name: "Papua Selatan" },
  { code: "94", name: "Papua" },
  { code: "95", name: "Papua Tengah" },
  { code: "96", name: "Papua Pegunungan" },
];

export const cities: City[] = [
  // ===== ACEH (11) =====
  { code: "01", name: "Simeulue", provinceCode: "11" },
  { code: "02", name: "Aceh Singkil", provinceCode: "11" },
  { code: "03", name: "Aceh Selatan", provinceCode: "11" },
  { code: "04", name: "Aceh Tenggara", provinceCode: "11" },
  { code: "05", name: "Aceh Timur", provinceCode: "11" },
  { code: "06", name: "Aceh Tengah", provinceCode: "11" },
  { code: "07", name: "Aceh Barat", provinceCode: "11" },
  { code: "08", name: "Aceh Besar", provinceCode: "11" },
  { code: "09", name: "Pidie", provinceCode: "11" },
  { code: "10", name: "Bireuen", provinceCode: "11" },
  { code: "11", name: "Aceh Utara", provinceCode: "11" },
  { code: "12", name: "Aceh Barat Daya", provinceCode: "11" },
  { code: "13", name: "Gayo Lues", provinceCode: "11" },
  { code: "14", name: "Aceh Tamiang", provinceCode: "11" },
  { code: "15", name: "Nagan Raya", provinceCode: "11" },
  { code: "16", name: "Aceh Jaya", provinceCode: "11" },
  { code: "17", name: "Bener Meriah", provinceCode: "11" },
  { code: "18", name: "Pidie Jaya", provinceCode: "11" },
  { code: "71", name: "Kota Banda Aceh", provinceCode: "11" },
  { code: "72", name: "Kota Sabang", provinceCode: "11" },
  { code: "73", name: "Kota Langsa", provinceCode: "11" },
  { code: "74", name: "Kota Lhokseumawe", provinceCode: "11" },
  { code: "75", name: "Kota Subulussalam", provinceCode: "11" },

  // ===== SUMATERA UTARA (12) =====
  { code: "01", name: "Nias", provinceCode: "12" },
  { code: "02", name: "Mandailing Natal", provinceCode: "12" },
  { code: "03", name: "Tapanuli Selatan", provinceCode: "12" },
  { code: "04", name: "Tapanuli Tengah", provinceCode: "12" },
  { code: "05", name: "Tapanuli Utara", provinceCode: "12" },
  { code: "06", name: "Toba Samosir", provinceCode: "12" },
  { code: "07", name: "Labuhanbatu", provinceCode: "12" },
  { code: "08", name: "Asahan", provinceCode: "12" },
  { code: "09", name: "Simalungun", provinceCode: "12" },
  { code: "10", name: "Dairi", provinceCode: "12" },
  { code: "11", name: "Karo", provinceCode: "12" },
  { code: "12", name: "Deli Serdang", provinceCode: "12" },
  { code: "13", name: "Langkat", provinceCode: "12" },
  { code: "14", name: "Nias Selatan", provinceCode: "12" },
  { code: "15", name: "Humbang Hasundutan", provinceCode: "12" },
  { code: "16", name: "Pakpak Bharat", provinceCode: "12" },
  { code: "17", name: "Samosir", provinceCode: "12" },
  { code: "18", name: "Serdang Bedagai", provinceCode: "12" },
  { code: "19", name: "Batu Bara", provinceCode: "12" },
  { code: "20", name: "Padang Lawas Utara", provinceCode: "12" },
  { code: "21", name: "Padang Lawas", provinceCode: "12" },
  { code: "22", name: "Labuhanbatu Selatan", provinceCode: "12" },
  { code: "23", name: "Labuhanbatu Utara", provinceCode: "12" },
  { code: "24", name: "Nias Utara", provinceCode: "12" },
  { code: "25", name: "Nias Barat", provinceCode: "12" },
  { code: "71", name: "Kota Sibolga", provinceCode: "12" },
  { code: "72", name: "Kota Tanjung Balai", provinceCode: "12" },
  { code: "73", name: "Kota Pematang Siantar", provinceCode: "12" },
  { code: "74", name: "Kota Tebing Tinggi", provinceCode: "12" },
  { code: "75", name: "Kota Medan", provinceCode: "12" },
  { code: "76", name: "Kota Binjai", provinceCode: "12" },
  { code: "77", name: "Kota Padangsidimpuan", provinceCode: "12" },
  { code: "78", name: "Kota Gunungsitoli", provinceCode: "12" },

  // ===== SUMATERA BARAT (13) =====
  { code: "01", name: "Kepulauan Mentawai", provinceCode: "13" },
  { code: "02", name: "Pesisir Selatan", provinceCode: "13" },
  { code: "03", name: "Solok", provinceCode: "13" },
  { code: "04", name: "Sijunjung", provinceCode: "13" },
  { code: "05", name: "Tanah Datar", provinceCode: "13" },
  { code: "06", name: "Padang Pariaman", provinceCode: "13" },
  { code: "07", name: "Agam", provinceCode: "13" },
  { code: "08", name: "Lima Puluh Kota", provinceCode: "13" },
  { code: "09", name: "Pasaman", provinceCode: "13" },
  { code: "10", name: "Solok Selatan", provinceCode: "13" },
  { code: "11", name: "Dharmasraya", provinceCode: "13" },
  { code: "12", name: "Pasaman Barat", provinceCode: "13" },
  { code: "71", name: "Kota Padang", provinceCode: "13" },
  { code: "72", name: "Kota Solok", provinceCode: "13" },
  { code: "73", name: "Kota Sawahlunto", provinceCode: "13" },
  { code: "74", name: "Kota Padang Panjang", provinceCode: "13" },
  { code: "75", name: "Kota Bukittinggi", provinceCode: "13" },
  { code: "76", name: "Kota Payakumbuh", provinceCode: "13" },
  { code: "77", name: "Kota Pariaman", provinceCode: "13" },

  // ===== RIAU (14) =====
  { code: "01", name: "Kuantan Singingi", provinceCode: "14" },
  { code: "02", name: "Indragiri Hulu", provinceCode: "14" },
  { code: "03", name: "Indragiri Hilir", provinceCode: "14" },
  { code: "04", name: "Pelalawan", provinceCode: "14" },
  { code: "05", name: "Siak", provinceCode: "14" },
  { code: "06", name: "Kampar", provinceCode: "14" },
  { code: "07", name: "Rokan Hulu", provinceCode: "14" },
  { code: "08", name: "Bengkalis", provinceCode: "14" },
  { code: "09", name: "Rokan Hilir", provinceCode: "14" },
  { code: "10", name: "Kepulauan Meranti", provinceCode: "14" },
  { code: "71", name: "Kota Pekanbaru", provinceCode: "14" },
  { code: "72", name: "Kota Dumai", provinceCode: "14" },

  // ===== JAMBI (15) =====
  { code: "01", name: "Kerinci", provinceCode: "15" },
  { code: "02", name: "Merangin", provinceCode: "15" },
  { code: "03", name: "Sarolangun", provinceCode: "15" },
  { code: "04", name: "Batang Hari", provinceCode: "15" },
  { code: "05", name: "Muaro Jambi", provinceCode: "15" },
  { code: "06", name: "Tanjung Jabung Timur", provinceCode: "15" },
  { code: "07", name: "Tanjung Jabung Barat", provinceCode: "15" },
  { code: "08", name: "Tebo", provinceCode: "15" },
  { code: "09", name: "Bungo", provinceCode: "15" },
  { code: "71", name: "Kota Jambi", provinceCode: "15" },
  { code: "72", name: "Kota Sungai Penuh", provinceCode: "15" },

  // ===== SUMATERA SELATAN (16) =====
  { code: "01", name: "Ogan Komering Ulu", provinceCode: "16" },
  { code: "02", name: "Ogan Komering Ilir", provinceCode: "16" },
  { code: "03", name: "Muara Enim", provinceCode: "16" },
  { code: "04", name: "Lahat", provinceCode: "16" },
  { code: "05", name: "Musi Rawas", provinceCode: "16" },
  { code: "06", name: "Musi Banyuasin", provinceCode: "16" },
  { code: "07", name: "Banyuasin", provinceCode: "16" },
  { code: "08", name: "Ogan Komering Ulu Selatan", provinceCode: "16" },
  { code: "09", name: "Ogan Komering Ulu Timur", provinceCode: "16" },
  { code: "10", name: "Ogan Ilir", provinceCode: "16" },
  { code: "11", name: "Empat Lawang", provinceCode: "16" },
  { code: "12", name: "Penukal Abab Lematang Ilir", provinceCode: "16" },
  { code: "13", name: "Musi Rawas Utara", provinceCode: "16" },
  { code: "71", name: "Kota Palembang", provinceCode: "16" },
  { code: "72", name: "Kota Prabumulih", provinceCode: "16" },
  { code: "73", name: "Kota Pagar Alam", provinceCode: "16" },
  { code: "74", name: "Kota Lubuklinggau", provinceCode: "16" },

  // ===== BENGKULU (17) =====
  { code: "01", name: "Bengkulu Selatan", provinceCode: "17" },
  { code: "02", name: "Rejang Lebong", provinceCode: "17" },
  { code: "03", name: "Bengkulu Utara", provinceCode: "17" },
  { code: "04", name: "Kaur", provinceCode: "17" },
  { code: "05", name: "Seluma", provinceCode: "17" },
  { code: "06", name: "Mukomuko", provinceCode: "17" },
  { code: "07", name: "Lebong", provinceCode: "17" },
  { code: "08", name: "Kepahiang", provinceCode: "17" },
  { code: "09", name: "Bengkulu Tengah", provinceCode: "17" },
  { code: "71", name: "Kota Bengkulu", provinceCode: "17" },

  // ===== LAMPUNG (18) =====
  { code: "01", name: "Lampung Barat", provinceCode: "18" },
  { code: "02", name: "Tanggamus", provinceCode: "18" },
  { code: "03", name: "Lampung Selatan", provinceCode: "18" },
  { code: "04", name: "Lampung Timur", provinceCode: "18" },
  { code: "05", name: "Lampung Tengah", provinceCode: "18" },
  { code: "06", name: "Lampung Utara", provinceCode: "18" },
  { code: "07", name: "Way Kanan", provinceCode: "18" },
  { code: "08", name: "Tulang Bawang", provinceCode: "18" },
  { code: "09", name: "Pesawaran", provinceCode: "18" },
  { code: "10", name: "Pringsewu", provinceCode: "18" },
  { code: "11", name: "Mesuji", provinceCode: "18" },
  { code: "12", name: "Tulang Bawang Barat", provinceCode: "18" },
  { code: "13", name: "Pesisir Barat", provinceCode: "18" },
  { code: "71", name: "Kota Bandar Lampung", provinceCode: "18" },
  { code: "72", name: "Kota Metro", provinceCode: "18" },

  // ===== KEPULAUAN BANGKA BELITUNG (19) =====
  { code: "01", name: "Bangka", provinceCode: "19" },
  { code: "02", name: "Belitung", provinceCode: "19" },
  { code: "03", name: "Bangka Barat", provinceCode: "19" },
  { code: "04", name: "Bangka Tengah", provinceCode: "19" },
  { code: "05", name: "Bangka Selatan", provinceCode: "19" },
  { code: "06", name: "Belitung Timur", provinceCode: "19" },
  { code: "71", name: "Kota Pangkal Pinang", provinceCode: "19" },

  // ===== KEPULAUAN RIAU (21) =====
  { code: "01", name: "Karimun", provinceCode: "21" },
  { code: "02", name: "Bintan", provinceCode: "21" },
  { code: "03", name: "Natuna", provinceCode: "21" },
  { code: "04", name: "Lingga", provinceCode: "21" },
  { code: "05", name: "Kepulauan Anambas", provinceCode: "21" },
  { code: "71", name: "Kota Batam", provinceCode: "21" },
  { code: "72", name: "Kota Tanjung Pinang", provinceCode: "21" },

  // ===== DKI JAKARTA (31) =====
  { code: "01", name: "Kepulauan Seribu", provinceCode: "31" },
  { code: "71", name: "Jakarta Selatan", provinceCode: "31" },
  { code: "72", name: "Jakarta Timur", provinceCode: "31" },
  { code: "73", name: "Jakarta Pusat", provinceCode: "31" },
  { code: "74", name: "Jakarta Barat", provinceCode: "31" },
  { code: "75", name: "Jakarta Utara", provinceCode: "31" },

  // ===== JAWA BARAT (32) =====
  { code: "01", name: "Bogor", provinceCode: "32" },
  { code: "02", name: "Sukabumi", provinceCode: "32" },
  { code: "03", name: "Cianjur", provinceCode: "32" },
  { code: "04", name: "Bandung", provinceCode: "32" },
  { code: "05", name: "Garut", provinceCode: "32" },
  { code: "06", name: "Tasikmalaya", provinceCode: "32" },
  { code: "07", name: "Ciamis", provinceCode: "32" },
  { code: "08", name: "Kuningan", provinceCode: "32" },
  { code: "09", name: "Cirebon", provinceCode: "32" },
  { code: "10", name: "Majalengka", provinceCode: "32" },
  { code: "11", name: "Sumedang", provinceCode: "32" },
  { code: "12", name: "Indramayu", provinceCode: "32" },
  { code: "13", name: "Subang", provinceCode: "32" },
  { code: "14", name: "Purwakarta", provinceCode: "32" },
  { code: "15", name: "Karawang", provinceCode: "32" },
  { code: "16", name: "Bekasi", provinceCode: "32" },
  { code: "17", name: "Bandung Barat", provinceCode: "32" },
  { code: "18", name: "Pangandaran", provinceCode: "32" },
  { code: "71", name: "Kota Bogor", provinceCode: "32" },
  { code: "72", name: "Kota Sukabumi", provinceCode: "32" },
  { code: "73", name: "Kota Bandung", provinceCode: "32" },
  { code: "74", name: "Kota Cirebon", provinceCode: "32" },
  { code: "75", name: "Kota Bekasi", provinceCode: "32" },
  { code: "76", name: "Kota Depok", provinceCode: "32" },
  { code: "77", name: "Kota Cimahi", provinceCode: "32" },
  { code: "78", name: "Kota Tasikmalaya", provinceCode: "32" },
  { code: "79", name: "Kota Banjar", provinceCode: "32" },

  // ===== JAWA TENGAH (33) =====
  { code: "01", name: "Cilacap", provinceCode: "33" },
  { code: "02", name: "Banyumas", provinceCode: "33" },
  { code: "03", name: "Purbalingga", provinceCode: "33" },
  { code: "04", name: "Banjarnegara", provinceCode: "33" },
  { code: "05", name: "Kebumen", provinceCode: "33" },
  { code: "06", name: "Purworejo", provinceCode: "33" },
  { code: "07", name: "Wonosobo", provinceCode: "33" },
  { code: "08", name: "Magelang", provinceCode: "33" },
  { code: "09", name: "Boyolali", provinceCode: "33" },
  { code: "10", name: "Klaten", provinceCode: "33" },
  { code: "11", name: "Sukoharjo", provinceCode: "33" },
  { code: "12", name: "Wonogiri", provinceCode: "33" },
  { code: "13", name: "Karanganyar", provinceCode: "33" },
  { code: "14", name: "Sragen", provinceCode: "33" },
  { code: "15", name: "Grobogan", provinceCode: "33" },
  { code: "16", name: "Blora", provinceCode: "33" },
  { code: "17", name: "Rembang", provinceCode: "33" },
  { code: "18", name: "Pati", provinceCode: "33" },
  { code: "19", name: "Kudus", provinceCode: "33" },
  { code: "20", name: "Jepara", provinceCode: "33" },
  { code: "21", name: "Demak", provinceCode: "33" },
  { code: "22", name: "Semarang", provinceCode: "33" },
  { code: "23", name: "Temanggung", provinceCode: "33" },
  { code: "24", name: "Kendal", provinceCode: "33" },
  { code: "25", name: "Batang", provinceCode: "33" },
  { code: "26", name: "Pekalongan", provinceCode: "33" },
  { code: "27", name: "Pemalang", provinceCode: "33" },
  { code: "28", name: "Tegal", provinceCode: "33" },
  { code: "29", name: "Brebes", provinceCode: "33" },
  { code: "71", name: "Kota Magelang", provinceCode: "33" },
  { code: "72", name: "Kota Surakarta", provinceCode: "33" },
  { code: "73", name: "Kota Salatiga", provinceCode: "33" },
  { code: "74", name: "Kota Semarang", provinceCode: "33" },
  { code: "75", name: "Kota Pekalongan", provinceCode: "33" },
  { code: "76", name: "Kota Tegal", provinceCode: "33" },

  // ===== DI YOGYAKARTA (34) =====
  { code: "01", name: "Kulon Progo", provinceCode: "34" },
  { code: "02", name: "Bantul", provinceCode: "34" },
  { code: "03", name: "Gunungkidul", provinceCode: "34" },
  { code: "04", name: "Sleman", provinceCode: "34" },
  { code: "71", name: "Kota Yogyakarta", provinceCode: "34" },

  // ===== JAWA TIMUR (35) =====
  { code: "01", name: "Pacitan", provinceCode: "35" },
  { code: "02", name: "Ponorogo", provinceCode: "35" },
  { code: "03", name: "Trenggalek", provinceCode: "35" },
  { code: "04", name: "Tulungagung", provinceCode: "35" },
  { code: "05", name: "Blitar", provinceCode: "35" },
  { code: "06", name: "Kediri", provinceCode: "35" },
  { code: "07", name: "Malang", provinceCode: "35" },
  { code: "08", name: "Lumajang", provinceCode: "35" },
  { code: "09", name: "Jember", provinceCode: "35" },
  { code: "10", name: "Banyuwangi", provinceCode: "35" },
  { code: "11", name: "Bondowoso", provinceCode: "35" },
  { code: "12", name: "Situbondo", provinceCode: "35" },
  { code: "13", name: "Probolinggo", provinceCode: "35" },
  { code: "14", name: "Pasuruan", provinceCode: "35" },
  { code: "15", name: "Sidoarjo", provinceCode: "35" },
  { code: "16", name: "Mojokerto", provinceCode: "35" },
  { code: "17", name: "Jombang", provinceCode: "35" },
  { code: "18", name: "Nganjuk", provinceCode: "35" },
  { code: "19", name: "Madiun", provinceCode: "35" },
  { code: "20", name: "Magetan", provinceCode: "35" },
  { code: "21", name: "Ngawi", provinceCode: "35" },
  { code: "22", name: "Bojonegoro", provinceCode: "35" },
  { code: "23", name: "Tuban", provinceCode: "35" },
  { code: "24", name: "Lamongan", provinceCode: "35" },
  { code: "25", name: "Gresik", provinceCode: "35" },
  { code: "26", name: "Bangkalan", provinceCode: "35" },
  { code: "27", name: "Sampang", provinceCode: "35" },
  { code: "28", name: "Pamekasan", provinceCode: "35" },
  { code: "29", name: "Sumenep", provinceCode: "35" },
  { code: "71", name: "Kota Kediri", provinceCode: "35" },
  { code: "72", name: "Kota Blitar", provinceCode: "35" },
  { code: "73", name: "Kota Malang", provinceCode: "35" },
  { code: "74", name: "Kota Probolinggo", provinceCode: "35" },
  { code: "75", name: "Kota Pasuruan", provinceCode: "35" },
  { code: "76", name: "Kota Mojokerto", provinceCode: "35" },
  { code: "77", name: "Kota Madiun", provinceCode: "35" },
  { code: "78", name: "Kota Surabaya", provinceCode: "35" },
  { code: "79", name: "Kota Batu", provinceCode: "35" },

  // ===== BANTEN (36) =====
  { code: "01", name: "Pandeglang", provinceCode: "36" },
  { code: "02", name: "Lebak", provinceCode: "36" },
  { code: "03", name: "Tangerang", provinceCode: "36" },
  { code: "04", name: "Serang", provinceCode: "36" },
  { code: "71", name: "Kota Tangerang", provinceCode: "36" },
  { code: "72", name: "Kota Cilegon", provinceCode: "36" },
  { code: "73", name: "Kota Serang", provinceCode: "36" },
  { code: "74", name: "Kota Tangerang Selatan", provinceCode: "36" },

  // ===== BALI (51) =====
  { code: "01", name: "Jembrana", provinceCode: "51" },
  { code: "02", name: "Tabanan", provinceCode: "51" },
  { code: "03", name: "Badung", provinceCode: "51" },
  { code: "04", name: "Gianyar", provinceCode: "51" },
  { code: "05", name: "Klungkung", provinceCode: "51" },
  { code: "06", name: "Bangli", provinceCode: "51" },
  { code: "07", name: "Karangasem", provinceCode: "51" },
  { code: "08", name: "Buleleng", provinceCode: "51" },
  { code: "71", name: "Kota Denpasar", provinceCode: "51" },

  // ===== NUSA TENGGARA BARAT (52) =====
  { code: "01", name: "Lombok Barat", provinceCode: "52" },
  { code: "02", name: "Lombok Tengah", provinceCode: "52" },
  { code: "03", name: "Lombok Timur", provinceCode: "52" },
  { code: "04", name: "Sumbawa", provinceCode: "52" },
  { code: "05", name: "Dompu", provinceCode: "52" },
  { code: "06", name: "Bima", provinceCode: "52" },
  { code: "07", name: "Sumbawa Barat", provinceCode: "52" },
  { code: "08", name: "Lombok Utara", provinceCode: "52" },
  { code: "71", name: "Kota Mataram", provinceCode: "52" },
  { code: "72", name: "Kota Bima", provinceCode: "52" },

  // ===== NUSA TENGGARA TIMUR (53) =====
  { code: "01", name: "Sumba Barat", provinceCode: "53" },
  { code: "02", name: "Sumba Timur", provinceCode: "53" },
  { code: "03", name: "Kupang", provinceCode: "53" },
  { code: "04", name: "Timor Tengah Selatan", provinceCode: "53" },
  { code: "05", name: "Timor Tengah Utara", provinceCode: "53" },
  { code: "06", name: "Belu", provinceCode: "53" },
  { code: "07", name: "Alor", provinceCode: "53" },
  { code: "08", name: "Lembata", provinceCode: "53" },
  { code: "09", name: "Flores Timur", provinceCode: "53" },
  { code: "10", name: "Sikka", provinceCode: "53" },
  { code: "11", name: "Ende", provinceCode: "53" },
  { code: "12", name: "Ngada", provinceCode: "53" },
  { code: "13", name: "Manggarai", provinceCode: "53" },
  { code: "14", name: "Rote Ndao", provinceCode: "53" },
  { code: "15", name: "Manggarai Barat", provinceCode: "53" },
  { code: "16", name: "Sumba Tengah", provinceCode: "53" },
  { code: "17", name: "Sumba Barat Daya", provinceCode: "53" },
  { code: "18", name: "Nagekeo", provinceCode: "53" },
  { code: "19", name: "Manggarai Timur", provinceCode: "53" },
  { code: "20", name: "Sabu Raijua", provinceCode: "53" },
  { code: "21", name: "Malaka", provinceCode: "53" },
  { code: "71", name: "Kota Kupang", provinceCode: "53" },

  // ===== KALIMANTAN BARAT (61) =====
  { code: "01", name: "Sambas", provinceCode: "61" },
  { code: "02", name: "Bengkayang", provinceCode: "61" },
  { code: "03", name: "Landak", provinceCode: "61" },
  { code: "04", name: "Mempawah", provinceCode: "61" },
  { code: "05", name: "Sanggau", provinceCode: "61" },
  { code: "06", name: "Ketapang", provinceCode: "61" },
  { code: "07", name: "Sintang", provinceCode: "61" },
  { code: "08", name: "Kapuas Hulu", provinceCode: "61" },
  { code: "09", name: "Sekadau", provinceCode: "61" },
  { code: "10", name: "Melawi", provinceCode: "61" },
  { code: "11", name: "Kayong Utara", provinceCode: "61" },
  { code: "12", name: "Kubu Raya", provinceCode: "61" },
  { code: "71", name: "Kota Pontianak", provinceCode: "61" },
  { code: "72", name: "Kota Singkawang", provinceCode: "61" },

  // ===== KALIMANTAN TENGAH (62) =====
  { code: "01", name: "Kotawaringin Barat", provinceCode: "62" },
  { code: "02", name: "Kotawaringin Timur", provinceCode: "62" },
  { code: "03", name: "Kapuas", provinceCode: "62" },
  { code: "04", name: "Barito Selatan", provinceCode: "62" },
  { code: "05", name: "Barito Utara", provinceCode: "62" },
  { code: "06", name: "Sukamara", provinceCode: "62" },
  { code: "07", name: "Lamandau", provinceCode: "62" },
  { code: "08", name: "Seruyan", provinceCode: "62" },
  { code: "09", name: "Katingan", provinceCode: "62" },
  { code: "10", name: "Pulang Pisau", provinceCode: "62" },
  { code: "11", name: "Gunung Mas", provinceCode: "62" },
  { code: "12", name: "Barito Timur", provinceCode: "62" },
  { code: "13", name: "Murung Raya", provinceCode: "62" },
  { code: "71", name: "Kota Palangka Raya", provinceCode: "62" },

  // ===== KALIMANTAN SELATAN (63) =====
  { code: "01", name: "Tanah Laut", provinceCode: "63" },
  { code: "02", name: "Kota Baru", provinceCode: "63" },
  { code: "03", name: "Banjar", provinceCode: "63" },
  { code: "04", name: "Barito Kuala", provinceCode: "63" },
  { code: "05", name: "Tapin", provinceCode: "63" },
  { code: "06", name: "Hulu Sungai Selatan", provinceCode: "63" },
  { code: "07", name: "Hulu Sungai Tengah", provinceCode: "63" },
  { code: "08", name: "Hulu Sungai Utara", provinceCode: "63" },
  { code: "09", name: "Tabalong", provinceCode: "63" },
  { code: "10", name: "Tanah Bumbu", provinceCode: "63" },
  { code: "11", name: "Balangan", provinceCode: "63" },
  { code: "71", name: "Kota Banjarmasin", provinceCode: "63" },
  { code: "72", name: "Kota Banjarbaru", provinceCode: "63" },

  // ===== KALIMANTAN TIMUR (64) =====
  { code: "01", name: "Paser", provinceCode: "64" },
  { code: "02", name: "Kutai Barat", provinceCode: "64" },
  { code: "03", name: "Kutai Kartanegara", provinceCode: "64" },
  { code: "04", name: "Kutai Timur", provinceCode: "64" },
  { code: "05", name: "Berau", provinceCode: "64" },
  { code: "06", name: "Penajam Paser Utara", provinceCode: "64" },
  { code: "07", name: "Mahakam Ulu", provinceCode: "64" },
  { code: "71", name: "Kota Balikpapan", provinceCode: "64" },
  { code: "72", name: "Kota Samarinda", provinceCode: "64" },
  { code: "74", name: "Kota Bontang", provinceCode: "64" },

  // ===== KALIMANTAN UTARA (65) =====
  { code: "01", name: "Malinau", provinceCode: "65" },
  { code: "02", name: "Bulungan", provinceCode: "65" },
  { code: "03", name: "Tana Tidung", provinceCode: "65" },
  { code: "04", name: "Nunukan", provinceCode: "65" },
  { code: "71", name: "Kota Tarakan", provinceCode: "65" },

  // ===== SULAWESI UTARA (71) =====
  { code: "01", name: "Bolaang Mongondow", provinceCode: "71" },
  { code: "02", name: "Minahasa", provinceCode: "71" },
  { code: "03", name: "Kepulauan Sangihe", provinceCode: "71" },
  { code: "04", name: "Kepulauan Talaud", provinceCode: "71" },
  { code: "05", name: "Minahasa Selatan", provinceCode: "71" },
  { code: "06", name: "Minahasa Utara", provinceCode: "71" },
  { code: "07", name: "Bolaang Mongondow Utara", provinceCode: "71" },
  { code: "08", name: "Kepulauan Siau Tagulandang Biaro", provinceCode: "71" },
  { code: "09", name: "Minahasa Tenggara", provinceCode: "71" },
  { code: "10", name: "Bolaang Mongondow Selatan", provinceCode: "71" },
  { code: "11", name: "Bolaang Mongondow Timur", provinceCode: "71" },
  { code: "71", name: "Kota Manado", provinceCode: "71" },
  { code: "72", name: "Kota Bitung", provinceCode: "71" },
  { code: "73", name: "Kota Tomohon", provinceCode: "71" },
  { code: "74", name: "Kota Kotamobagu", provinceCode: "71" },

  // ===== SULAWESI TENGAH (72) =====
  { code: "01", name: "Banggai Kepulauan", provinceCode: "72" },
  { code: "02", name: "Banggai", provinceCode: "72" },
  { code: "03", name: "Morowali", provinceCode: "72" },
  { code: "04", name: "Poso", provinceCode: "72" },
  { code: "05", name: "Donggala", provinceCode: "72" },
  { code: "06", name: "Toli-Toli", provinceCode: "72" },
  { code: "07", name: "Buol", provinceCode: "72" },
  { code: "08", name: "Parigi Moutong", provinceCode: "72" },
  { code: "09", name: "Tojo Una-Una", provinceCode: "72" },
  { code: "10", name: "Sigi", provinceCode: "72" },
  { code: "11", name: "Banggai Laut", provinceCode: "72" },
  { code: "12", name: "Morowali Utara", provinceCode: "72" },
  { code: "71", name: "Kota Palu", provinceCode: "72" },

  // ===== SULAWESI SELATAN (73) =====
  { code: "01", name: "Selayar", provinceCode: "73" },
  { code: "02", name: "Bulukumba", provinceCode: "73" },
  { code: "03", name: "Bantaeng", provinceCode: "73" },
  { code: "04", name: "Jeneponto", provinceCode: "73" },
  { code: "05", name: "Takalar", provinceCode: "73" },
  { code: "06", name: "Gowa", provinceCode: "73" },
  { code: "07", name: "Sinjai", provinceCode: "73" },
  { code: "08", name: "Maros", provinceCode: "73" },
  { code: "09", name: "Pangkajene dan Kepulauan", provinceCode: "73" },
  { code: "10", name: "Barru", provinceCode: "73" },
  { code: "11", name: "Bone", provinceCode: "73" },
  { code: "12", name: "Soppeng", provinceCode: "73" },
  { code: "13", name: "Wajo", provinceCode: "73" },
  { code: "14", name: "Sidenreng Rappang", provinceCode: "73" },
  { code: "15", name: "Pinrang", provinceCode: "73" },
  { code: "16", name: "Enrekang", provinceCode: "73" },
  { code: "17", name: "Luwu", provinceCode: "73" },
  { code: "18", name: "Tana Toraja", provinceCode: "73" },
  { code: "22", name: "Luwu Utara", provinceCode: "73" },
  { code: "24", name: "Luwu Timur", provinceCode: "73" },
  { code: "26", name: "Toraja Utara", provinceCode: "73" },
  { code: "71", name: "Kota Makassar", provinceCode: "73" },
  { code: "72", name: "Kota Parepare", provinceCode: "73" },
  { code: "73", name: "Kota Palopo", provinceCode: "73" },

  // ===== SULAWESI TENGGARA (74) =====
  { code: "01", name: "Buton", provinceCode: "74" },
  { code: "02", name: "Muna", provinceCode: "74" },
  { code: "03", name: "Konawe", provinceCode: "74" },
  { code: "04", name: "Kolaka", provinceCode: "74" },
  { code: "05", name: "Konawe Selatan", provinceCode: "74" },
  { code: "06", name: "Bombana", provinceCode: "74" },
  { code: "07", name: "Wakatobi", provinceCode: "74" },
  { code: "08", name: "Kolaka Utara", provinceCode: "74" },
  { code: "09", name: "Buton Utara", provinceCode: "74" },
  { code: "10", name: "Konawe Utara", provinceCode: "74" },
  { code: "11", name: "Kolaka Timur", provinceCode: "74" },
  { code: "12", name: "Konawe Kepulauan", provinceCode: "74" },
  { code: "13", name: "Muna Barat", provinceCode: "74" },
  { code: "14", name: "Buton Tengah", provinceCode: "74" },
  { code: "15", name: "Buton Selatan", provinceCode: "74" },
  { code: "71", name: "Kota Kendari", provinceCode: "74" },
  { code: "72", name: "Kota Bau-Bau", provinceCode: "74" },

  // ===== GORONTALO (75) =====
  { code: "01", name: "Boalemo", provinceCode: "75" },
  { code: "02", name: "Gorontalo", provinceCode: "75" },
  { code: "03", name: "Pohuwato", provinceCode: "75" },
  { code: "04", name: "Bone Bolango", provinceCode: "75" },
  { code: "05", name: "Gorontalo Utara", provinceCode: "75" },
  { code: "71", name: "Kota Gorontalo", provinceCode: "75" },

  // ===== SULAWESI BARAT (76) =====
  { code: "01", name: "Majene", provinceCode: "76" },
  { code: "02", name: "Polewali Mandar", provinceCode: "76" },
  { code: "03", name: "Mamasa", provinceCode: "76" },
  { code: "04", name: "Mamuju", provinceCode: "76" },
  { code: "05", name: "Mamuju Utara", provinceCode: "76" },
  { code: "06", name: "Mamuju Tengah", provinceCode: "76" },

  // ===== MALUKU (81) =====
  { code: "01", name: "Maluku Tenggara Barat", provinceCode: "81" },
  { code: "02", name: "Maluku Tenggara", provinceCode: "81" },
  { code: "03", name: "Maluku Tengah", provinceCode: "81" },
  { code: "04", name: "Buru", provinceCode: "81" },
  { code: "05", name: "Kepulauan Aru", provinceCode: "81" },
  { code: "06", name: "Seram Bagian Barat", provinceCode: "81" },
  { code: "07", name: "Seram Bagian Timur", provinceCode: "81" },
  { code: "08", name: "Maluku Barat Daya", provinceCode: "81" },
  { code: "09", name: "Buru Selatan", provinceCode: "81" },
  { code: "71", name: "Kota Ambon", provinceCode: "81" },
  { code: "72", name: "Kota Tual", provinceCode: "81" },

  // ===== MALUKU UTARA (82) =====
  { code: "01", name: "Halmahera Barat", provinceCode: "82" },
  { code: "02", name: "Halmahera Tengah", provinceCode: "82" },
  { code: "03", name: "Kepulauan Sula", provinceCode: "82" },
  { code: "04", name: "Halmahera Selatan", provinceCode: "82" },
  { code: "05", name: "Halmahera Utara", provinceCode: "82" },
  { code: "06", name: "Halmahera Timur", provinceCode: "82" },
  { code: "07", name: "Pulau Morotai", provinceCode: "82" },
  { code: "08", name: "Pulau Taliabu", provinceCode: "82" },
  { code: "71", name: "Kota Ternate", provinceCode: "82" },
  { code: "72", name: "Kota Tidore Kepulauan", provinceCode: "82" },

  // ===== PAPUA BARAT (91) =====
  { code: "01", name: "Fakfak", provinceCode: "91" },
  { code: "02", name: "Kaimana", provinceCode: "91" },
  { code: "03", name: "Teluk Wondama", provinceCode: "91" },
  { code: "04", name: "Teluk Bintuni", provinceCode: "91" },
  { code: "05", name: "Manokwari", provinceCode: "91" },
  { code: "06", name: "Sorong Selatan", provinceCode: "91" },
  { code: "07", name: "Sorong", provinceCode: "91" },
  { code: "08", name: "Raja Ampat", provinceCode: "91" },
  { code: "09", name: "Tambrauw", provinceCode: "91" },
  { code: "10", name: "Maybrat", provinceCode: "91" },
  { code: "11", name: "Manokwari Selatan", provinceCode: "91" },
  { code: "12", name: "Pegunungan Arfak", provinceCode: "91" },
  { code: "71", name: "Kota Sorong", provinceCode: "91" },

  // ===== PAPUA (94) =====
  { code: "01", name: "Merauke", provinceCode: "94" },
  { code: "02", name: "Jayawijaya", provinceCode: "94" },
  { code: "03", name: "Jayapura", provinceCode: "94" },
  { code: "04", name: "Nabire", provinceCode: "94" },
  { code: "05", name: "Kepulauan Yapen", provinceCode: "94" },
  { code: "06", name: "Biak Numfor", provinceCode: "94" },
  { code: "07", name: "Paniai", provinceCode: "94" },
  { code: "08", name: "Puncak Jaya", provinceCode: "94" },
  { code: "09", name: "Mimika", provinceCode: "94" },
  { code: "10", name: "Boven Digoel", provinceCode: "94" },
  { code: "11", name: "Mappi", provinceCode: "94" },
  { code: "12", name: "Asmat", provinceCode: "94" },
  { code: "13", name: "Yahukimo", provinceCode: "94" },
  { code: "14", name: "Pegunungan Bintang", provinceCode: "94" },
  { code: "15", name: "Tolikara", provinceCode: "94" },
  { code: "16", name: "Sarmi", provinceCode: "94" },
  { code: "17", name: "Keerom", provinceCode: "94" },
  { code: "18", name: "Waropen", provinceCode: "94" },
  { code: "19", name: "Supiori", provinceCode: "94" },
  { code: "20", name: "Mamberamo Raya", provinceCode: "94" },
  { code: "21", name: "Nduga", provinceCode: "94" },
  { code: "22", name: "Lanny Jaya", provinceCode: "94" },
  { code: "23", name: "Mamberamo Tengah", provinceCode: "94" },
  { code: "24", name: "Yalimo", provinceCode: "94" },
  { code: "25", name: "Puncak", provinceCode: "94" },
  { code: "26", name: "Dogiyai", provinceCode: "94" },
  { code: "27", name: "Intan Jaya", provinceCode: "94" },
  { code: "28", name: "Deiyai", provinceCode: "94" },
  { code: "71", name: "Kota Jayapura", provinceCode: "94" },
];

export function getProvinceName(code: string): string | null {
  const province = provinces.find(p => p.code === code);
  return province ? province.name : null;
}

export function getCityName(provinceCode: string, cityCode: string): string | null {
  const city = cities.find(c => c.provinceCode === provinceCode && c.code === cityCode);
  return city ? city.name : null;
}

export function isValidProvinceCode(code: string): boolean {
  return provinces.some(p => p.code === code);
}

export function isValidCityCode(provinceCode: string, cityCode: string): boolean {
  return cities.some(c => c.provinceCode === provinceCode && c.code === cityCode);
}
