// Data wilayah Indonesia berdasarkan kode Kemendagri (digunakan dalam NIK)
// Sumber: https://github.com/fityannugroho/idn-area-data

export interface Province {
  code: string;
  name: string;
}

export interface City {
  code: string;
  name: string;
  provinceCode: string;
}

export const provinces: Province[] = [
  { code: "11", name: "Aceh" },
  { code: "12", name: "Sumatera Utara" },
  { code: "13", name: "Sumatera Barat" },
  { code: "14", name: "Riau" },
  { code: "15", name: "Jambi" },
  { code: "16", name: "Sumatera Selatan" },
  { code: "17", name: "Bengkulu" },
  { code: "18", name: "Lampung" },
  { code: "19", name: "Kepulauan Bangka Belitung" },
  { code: "21", name: "Kepulauan Riau" },
  { code: "31", name: "DKI Jakarta" },
  { code: "32", name: "Jawa Barat" },
  { code: "33", name: "Jawa Tengah" },
  { code: "34", name: "DI Yogyakarta" },
  { code: "35", name: "Jawa Timur" },
  { code: "36", name: "Banten" },
  { code: "51", name: "Bali" },
  { code: "52", name: "Nusa Tenggara Barat" },
  { code: "53", name: "Nusa Tenggara Timur" },
  { code: "61", name: "Kalimantan Barat" },
  { code: "62", name: "Kalimantan Tengah" },
  { code: "63", name: "Kalimantan Selatan" },
  { code: "64", name: "Kalimantan Timur" },
  { code: "65", name: "Kalimantan Utara" },
  { code: "71", name: "Sulawesi Utara" },
  { code: "72", name: "Sulawesi Tengah" },
  { code: "73", name: "Sulawesi Selatan" },
  { code: "74", name: "Sulawesi Tenggara" },
  { code: "75", name: "Gorontalo" },
  { code: "76", name: "Sulawesi Barat" },
  { code: "81", name: "Maluku" },
  { code: "82", name: "Maluku Utara" },
  { code: "91", name: "Papua" },
  { code: "92", name: "Papua Barat" },
  { code: "93", name: "Papua Selatan" },
  { code: "94", name: "Papua Tengah" },
  { code: "95", name: "Papua Pegunungan" },
  { code: "96", name: "Papua Barat Daya" },
];

// Kode Kabupaten/Kota menggunakan kode Kemendagri (sesuai NIK)
export const cities: City[] = [
  // ===== ACEH (11) =====
  { code: "01", name: "Kabupaten Aceh Selatan", provinceCode: "11" },
  { code: "02", name: "Kabupaten Aceh Tenggara", provinceCode: "11" },
  { code: "03", name: "Kabupaten Aceh Timur", provinceCode: "11" },
  { code: "04", name: "Kabupaten Aceh Tengah", provinceCode: "11" },
  { code: "05", name: "Kabupaten Aceh Barat", provinceCode: "11" },
  { code: "06", name: "Kabupaten Aceh Besar", provinceCode: "11" },
  { code: "07", name: "Kabupaten Pidie", provinceCode: "11" },
  { code: "08", name: "Kabupaten Aceh Utara", provinceCode: "11" },
  { code: "09", name: "Kabupaten Simeulue", provinceCode: "11" },
  { code: "10", name: "Kabupaten Aceh Singkil", provinceCode: "11" },
  { code: "11", name: "Kabupaten Bireuen", provinceCode: "11" },
  { code: "12", name: "Kabupaten Aceh Barat Daya", provinceCode: "11" },
  { code: "13", name: "Kabupaten Gayo Lues", provinceCode: "11" },
  { code: "14", name: "Kabupaten Aceh Jaya", provinceCode: "11" },
  { code: "15", name: "Kabupaten Nagan Raya", provinceCode: "11" },
  { code: "16", name: "Kabupaten Aceh Tamiang", provinceCode: "11" },
  { code: "17", name: "Kabupaten Bener Meriah", provinceCode: "11" },
  { code: "18", name: "Kabupaten Pidie Jaya", provinceCode: "11" },
  { code: "71", name: "Kota Banda Aceh", provinceCode: "11" },
  { code: "72", name: "Kota Sabang", provinceCode: "11" },
  { code: "73", name: "Kota Lhokseumawe", provinceCode: "11" },
  { code: "74", name: "Kota Langsa", provinceCode: "11" },
  { code: "75", name: "Kota Subulussalam", provinceCode: "11" },

  // ===== SUMATERA UTARA (12) =====
  { code: "01", name: "Kabupaten Tapanuli Tengah", provinceCode: "12" },
  { code: "02", name: "Kabupaten Tapanuli Utara", provinceCode: "12" },
  { code: "03", name: "Kabupaten Tapanuli Selatan", provinceCode: "12" },
  { code: "04", name: "Kabupaten Nias", provinceCode: "12" },
  { code: "05", name: "Kabupaten Langkat", provinceCode: "12" },
  { code: "06", name: "Kabupaten Karo", provinceCode: "12" },
  { code: "07", name: "Kabupaten Deli Serdang", provinceCode: "12" },
  { code: "08", name: "Kabupaten Simalungun", provinceCode: "12" },
  { code: "09", name: "Kabupaten Asahan", provinceCode: "12" },
  { code: "10", name: "Kabupaten Labuhanbatu", provinceCode: "12" },
  { code: "11", name: "Kabupaten Dairi", provinceCode: "12" },
  { code: "12", name: "Kabupaten Toba", provinceCode: "12" },
  { code: "13", name: "Kabupaten Mandailing Natal", provinceCode: "12" },
  { code: "14", name: "Kabupaten Nias Selatan", provinceCode: "12" },
  { code: "15", name: "Kabupaten Pakpak Bharat", provinceCode: "12" },
  { code: "16", name: "Kabupaten Humbang Hasundutan", provinceCode: "12" },
  { code: "17", name: "Kabupaten Samosir", provinceCode: "12" },
  { code: "18", name: "Kabupaten Serdang Bedagai", provinceCode: "12" },
  { code: "19", name: "Kabupaten Batu Bara", provinceCode: "12" },
  { code: "20", name: "Kabupaten Padang Lawas Utara", provinceCode: "12" },
  { code: "21", name: "Kabupaten Padang Lawas", provinceCode: "12" },
  { code: "22", name: "Kabupaten Labuhanbatu Selatan", provinceCode: "12" },
  { code: "23", name: "Kabupaten Labuhanbatu Utara", provinceCode: "12" },
  { code: "24", name: "Kabupaten Nias Utara", provinceCode: "12" },
  { code: "25", name: "Kabupaten Nias Barat", provinceCode: "12" },
  { code: "71", name: "Kota Medan", provinceCode: "12" },
  { code: "72", name: "Kota Pematangsiantar", provinceCode: "12" },
  { code: "73", name: "Kota Sibolga", provinceCode: "12" },
  { code: "74", name: "Kota Tanjungbalai", provinceCode: "12" },
  { code: "75", name: "Kota Binjai", provinceCode: "12" },
  { code: "76", name: "Kota Tebing Tinggi", provinceCode: "12" },
  { code: "77", name: "Kota Padangsidimpuan", provinceCode: "12" },
  { code: "78", name: "Kota Gunungsitoli", provinceCode: "12" },

  // ===== SUMATERA BARAT (13) =====
  { code: "01", name: "Kabupaten Pesisir Selatan", provinceCode: "13" },
  { code: "02", name: "Kabupaten Solok", provinceCode: "13" },
  { code: "03", name: "Kabupaten Sijunjung", provinceCode: "13" },
  { code: "04", name: "Kabupaten Tanah Datar", provinceCode: "13" },
  { code: "05", name: "Kabupaten Padang Pariaman", provinceCode: "13" },
  { code: "06", name: "Kabupaten Agam", provinceCode: "13" },
  { code: "07", name: "Kabupaten Lima Puluh Kota", provinceCode: "13" },
  { code: "08", name: "Kabupaten Pasaman", provinceCode: "13" },
  { code: "09", name: "Kabupaten Kepulauan Mentawai", provinceCode: "13" },
  { code: "10", name: "Kabupaten Dharmasraya", provinceCode: "13" },
  { code: "11", name: "Kabupaten Solok Selatan", provinceCode: "13" },
  { code: "12", name: "Kabupaten Pasaman Barat", provinceCode: "13" },
  { code: "71", name: "Kota Padang", provinceCode: "13" },
  { code: "72", name: "Kota Solok", provinceCode: "13" },
  { code: "73", name: "Kota Sawahlunto", provinceCode: "13" },
  { code: "74", name: "Kota Padang Panjang", provinceCode: "13" },
  { code: "75", name: "Kota Bukittinggi", provinceCode: "13" },
  { code: "76", name: "Kota Payakumbuh", provinceCode: "13" },
  { code: "77", name: "Kota Pariaman", provinceCode: "13" },

  // ===== RIAU (14) =====
  { code: "01", name: "Kabupaten Kampar", provinceCode: "14" },
  { code: "02", name: "Kabupaten Indragiri Hulu", provinceCode: "14" },
  { code: "03", name: "Kabupaten Bengkalis", provinceCode: "14" },
  { code: "04", name: "Kabupaten Indragiri Hilir", provinceCode: "14" },
  { code: "05", name: "Kabupaten Pelalawan", provinceCode: "14" },
  { code: "06", name: "Kabupaten Rokan Hulu", provinceCode: "14" },
  { code: "07", name: "Kabupaten Rokan Hilir", provinceCode: "14" },
  { code: "08", name: "Kabupaten Siak", provinceCode: "14" },
  { code: "09", name: "Kabupaten Kuantan Singingi", provinceCode: "14" },
  { code: "10", name: "Kabupaten Kepulauan Meranti", provinceCode: "14" },
  { code: "71", name: "Kota Pekanbaru", provinceCode: "14" },
  { code: "72", name: "Kota Dumai", provinceCode: "14" },

  // ===== JAMBI (15) =====
  { code: "01", name: "Kabupaten Kerinci", provinceCode: "15" },
  { code: "02", name: "Kabupaten Merangin", provinceCode: "15" },
  { code: "03", name: "Kabupaten Sarolangun", provinceCode: "15" },
  { code: "04", name: "Kabupaten Batanghari", provinceCode: "15" },
  { code: "05", name: "Kabupaten Muaro Jambi", provinceCode: "15" },
  { code: "06", name: "Kabupaten Tanjung Jabung Barat", provinceCode: "15" },
  { code: "07", name: "Kabupaten Tanjung Jabung Timur", provinceCode: "15" },
  { code: "08", name: "Kabupaten Bungo", provinceCode: "15" },
  { code: "09", name: "Kabupaten Tebo", provinceCode: "15" },
  { code: "71", name: "Kota Jambi", provinceCode: "15" },
  { code: "72", name: "Kota Sungai Penuh", provinceCode: "15" },

  // ===== SUMATERA SELATAN (16) =====
  { code: "01", name: "Kabupaten Ogan Komering Ulu", provinceCode: "16" },
  { code: "02", name: "Kabupaten Ogan Komering Ilir", provinceCode: "16" },
  { code: "03", name: "Kabupaten Muara Enim", provinceCode: "16" },
  { code: "04", name: "Kabupaten Lahat", provinceCode: "16" },
  { code: "05", name: "Kabupaten Musi Rawas", provinceCode: "16" },
  { code: "06", name: "Kabupaten Musi Banyuasin", provinceCode: "16" },
  { code: "07", name: "Kabupaten Banyuasin", provinceCode: "16" },
  { code: "08", name: "Kabupaten OKU Timur", provinceCode: "16" },
  { code: "09", name: "Kabupaten OKU Selatan", provinceCode: "16" },
  { code: "10", name: "Kabupaten Ogan Ilir", provinceCode: "16" },
  { code: "11", name: "Kabupaten Empat Lawang", provinceCode: "16" },
  { code: "12", name: "Kabupaten PALI", provinceCode: "16" },
  { code: "13", name: "Kabupaten Musi Rawas Utara", provinceCode: "16" },
  { code: "71", name: "Kota Palembang", provinceCode: "16" },
  { code: "72", name: "Kota Pagar Alam", provinceCode: "16" },
  { code: "73", name: "Kota Lubuk Linggau", provinceCode: "16" },
  { code: "74", name: "Kota Prabumulih", provinceCode: "16" },

  // ===== BENGKULU (17) =====
  { code: "01", name: "Kabupaten Bengkulu Selatan", provinceCode: "17" },
  { code: "02", name: "Kabupaten Rejang Lebong", provinceCode: "17" },
  { code: "03", name: "Kabupaten Bengkulu Utara", provinceCode: "17" },
  { code: "04", name: "Kabupaten Kaur", provinceCode: "17" },
  { code: "05", name: "Kabupaten Seluma", provinceCode: "17" },
  { code: "06", name: "Kabupaten Mukomuko", provinceCode: "17" },
  { code: "07", name: "Kabupaten Lebong", provinceCode: "17" },
  { code: "08", name: "Kabupaten Kepahiang", provinceCode: "17" },
  { code: "09", name: "Kabupaten Bengkulu Tengah", provinceCode: "17" },
  { code: "71", name: "Kota Bengkulu", provinceCode: "17" },

  // ===== LAMPUNG (18) =====
  { code: "01", name: "Kabupaten Lampung Selatan", provinceCode: "18" },
  { code: "02", name: "Kabupaten Lampung Tengah", provinceCode: "18" },
  { code: "03", name: "Kabupaten Lampung Utara", provinceCode: "18" },
  { code: "04", name: "Kabupaten Lampung Barat", provinceCode: "18" },
  { code: "05", name: "Kabupaten Tulang Bawang", provinceCode: "18" },
  { code: "06", name: "Kabupaten Tanggamus", provinceCode: "18" },
  { code: "07", name: "Kabupaten Lampung Timur", provinceCode: "18" },
  { code: "08", name: "Kabupaten Way Kanan", provinceCode: "18" },
  { code: "09", name: "Kabupaten Pesawaran", provinceCode: "18" },
  { code: "10", name: "Kabupaten Pringsewu", provinceCode: "18" },
  { code: "11", name: "Kabupaten Mesuji", provinceCode: "18" },
  { code: "12", name: "Kabupaten Tulang Bawang Barat", provinceCode: "18" },
  { code: "13", name: "Kabupaten Pesisir Barat", provinceCode: "18" },
  { code: "71", name: "Kota Bandar Lampung", provinceCode: "18" },
  { code: "72", name: "Kota Metro", provinceCode: "18" },

  // ===== KEPULAUAN BANGKA BELITUNG (19) =====
  { code: "01", name: "Kabupaten Bangka", provinceCode: "19" },
  { code: "02", name: "Kabupaten Belitung", provinceCode: "19" },
  { code: "03", name: "Kabupaten Bangka Selatan", provinceCode: "19" },
  { code: "04", name: "Kabupaten Bangka Tengah", provinceCode: "19" },
  { code: "05", name: "Kabupaten Bangka Barat", provinceCode: "19" },
  { code: "06", name: "Kabupaten Belitung Timur", provinceCode: "19" },
  { code: "71", name: "Kota Pangkal Pinang", provinceCode: "19" },

  // ===== KEPULAUAN RIAU (21) =====
  { code: "01", name: "Kabupaten Bintan", provinceCode: "21" },
  { code: "02", name: "Kabupaten Karimun", provinceCode: "21" },
  { code: "03", name: "Kabupaten Natuna", provinceCode: "21" },
  { code: "04", name: "Kabupaten Lingga", provinceCode: "21" },
  { code: "05", name: "Kabupaten Kepulauan Anambas", provinceCode: "21" },
  { code: "71", name: "Kota Batam", provinceCode: "21" },
  { code: "72", name: "Kota Tanjung Pinang", provinceCode: "21" },

  // ===== DKI JAKARTA (31) =====
  { code: "01", name: "Kabupaten Kepulauan Seribu", provinceCode: "31" },
  { code: "71", name: "Kota Jakarta Pusat", provinceCode: "31" },
  { code: "72", name: "Kota Jakarta Utara", provinceCode: "31" },
  { code: "73", name: "Kota Jakarta Barat", provinceCode: "31" },
  { code: "74", name: "Kota Jakarta Selatan", provinceCode: "31" },
  { code: "75", name: "Kota Jakarta Timur", provinceCode: "31" },

  // ===== JAWA BARAT (32) =====
  { code: "01", name: "Kabupaten Bogor", provinceCode: "32" },
  { code: "02", name: "Kabupaten Sukabumi", provinceCode: "32" },
  { code: "03", name: "Kabupaten Cianjur", provinceCode: "32" },
  { code: "04", name: "Kabupaten Bandung", provinceCode: "32" },
  { code: "05", name: "Kabupaten Garut", provinceCode: "32" },
  { code: "06", name: "Kabupaten Tasikmalaya", provinceCode: "32" },
  { code: "07", name: "Kabupaten Ciamis", provinceCode: "32" },
  { code: "08", name: "Kabupaten Kuningan", provinceCode: "32" },
  { code: "09", name: "Kabupaten Cirebon", provinceCode: "32" },
  { code: "10", name: "Kabupaten Majalengka", provinceCode: "32" },
  { code: "11", name: "Kabupaten Sumedang", provinceCode: "32" },
  { code: "12", name: "Kabupaten Indramayu", provinceCode: "32" },
  { code: "13", name: "Kabupaten Subang", provinceCode: "32" },
  { code: "14", name: "Kabupaten Purwakarta", provinceCode: "32" },
  { code: "15", name: "Kabupaten Karawang", provinceCode: "32" },
  { code: "16", name: "Kabupaten Bekasi", provinceCode: "32" },
  { code: "17", name: "Kabupaten Bandung Barat", provinceCode: "32" },
  { code: "18", name: "Kabupaten Pangandaran", provinceCode: "32" },
  { code: "71", name: "Kota Bogor", provinceCode: "32" },
  { code: "72", name: "Kota Sukabumi", provinceCode: "32" },
  { code: "73", name: "Kota Bandung", provinceCode: "32" },
  { code: "74", name: "Kota Cirebon", provinceCode: "32" },
  { code: "75", name: "Kota Bekasi", provinceCode: "32" },
  { code: "76", name: "Kota Depok", provinceCode: "32" },
  { code: "77", name: "Kota Cimahi", provinceCode: "32" },
  { code: "78", name: "Kota Tasikmalaya", provinceCode: "32" },
  { code: "79", name: "Kota Banjar", provinceCode: "32" },

  // ===== JAWA TENGAH (33) =====
  { code: "01", name: "Kabupaten Cilacap", provinceCode: "33" },
  { code: "02", name: "Kabupaten Banyumas", provinceCode: "33" },
  { code: "03", name: "Kabupaten Purbalingga", provinceCode: "33" },
  { code: "04", name: "Kabupaten Banjarnegara", provinceCode: "33" },
  { code: "05", name: "Kabupaten Kebumen", provinceCode: "33" },
  { code: "06", name: "Kabupaten Purworejo", provinceCode: "33" },
  { code: "07", name: "Kabupaten Wonosobo", provinceCode: "33" },
  { code: "08", name: "Kabupaten Magelang", provinceCode: "33" },
  { code: "09", name: "Kabupaten Boyolali", provinceCode: "33" },
  { code: "10", name: "Kabupaten Klaten", provinceCode: "33" },
  { code: "11", name: "Kabupaten Sukoharjo", provinceCode: "33" },
  { code: "12", name: "Kabupaten Wonogiri", provinceCode: "33" },
  { code: "13", name: "Kabupaten Karanganyar", provinceCode: "33" },
  { code: "14", name: "Kabupaten Sragen", provinceCode: "33" },
  { code: "15", name: "Kabupaten Grobogan", provinceCode: "33" },
  { code: "16", name: "Kabupaten Blora", provinceCode: "33" },
  { code: "17", name: "Kabupaten Rembang", provinceCode: "33" },
  { code: "18", name: "Kabupaten Pati", provinceCode: "33" },
  { code: "19", name: "Kabupaten Kudus", provinceCode: "33" },
  { code: "20", name: "Kabupaten Jepara", provinceCode: "33" },
  { code: "21", name: "Kabupaten Demak", provinceCode: "33" },
  { code: "22", name: "Kabupaten Semarang", provinceCode: "33" },
  { code: "23", name: "Kabupaten Temanggung", provinceCode: "33" },
  { code: "24", name: "Kabupaten Kendal", provinceCode: "33" },
  { code: "25", name: "Kabupaten Batang", provinceCode: "33" },
  { code: "26", name: "Kabupaten Pekalongan", provinceCode: "33" },
  { code: "27", name: "Kabupaten Pemalang", provinceCode: "33" },
  { code: "28", name: "Kabupaten Tegal", provinceCode: "33" },
  { code: "29", name: "Kabupaten Brebes", provinceCode: "33" },
  { code: "71", name: "Kota Magelang", provinceCode: "33" },
  { code: "72", name: "Kota Surakarta", provinceCode: "33" },
  { code: "73", name: "Kota Salatiga", provinceCode: "33" },
  { code: "74", name: "Kota Semarang", provinceCode: "33" },
  { code: "75", name: "Kota Pekalongan", provinceCode: "33" },
  { code: "76", name: "Kota Tegal", provinceCode: "33" },

  // ===== DI YOGYAKARTA (34) =====
  { code: "01", name: "Kabupaten Kulon Progo", provinceCode: "34" },
  { code: "02", name: "Kabupaten Bantul", provinceCode: "34" },
  { code: "03", name: "Kabupaten Gunungkidul", provinceCode: "34" },
  { code: "04", name: "Kabupaten Sleman", provinceCode: "34" },
  { code: "71", name: "Kota Yogyakarta", provinceCode: "34" },

  // ===== JAWA TIMUR (35) =====
  { code: "01", name: "Kabupaten Pacitan", provinceCode: "35" },
  { code: "02", name: "Kabupaten Ponorogo", provinceCode: "35" },
  { code: "03", name: "Kabupaten Trenggalek", provinceCode: "35" },
  { code: "04", name: "Kabupaten Tulungagung", provinceCode: "35" },
  { code: "05", name: "Kabupaten Blitar", provinceCode: "35" },
  { code: "06", name: "Kabupaten Kediri", provinceCode: "35" },
  { code: "07", name: "Kabupaten Malang", provinceCode: "35" },
  { code: "08", name: "Kabupaten Lumajang", provinceCode: "35" },
  { code: "09", name: "Kabupaten Jember", provinceCode: "35" },
  { code: "10", name: "Kabupaten Banyuwangi", provinceCode: "35" },
  { code: "11", name: "Kabupaten Bondowoso", provinceCode: "35" },
  { code: "12", name: "Kabupaten Situbondo", provinceCode: "35" },
  { code: "13", name: "Kabupaten Probolinggo", provinceCode: "35" },
  { code: "14", name: "Kabupaten Pasuruan", provinceCode: "35" },
  { code: "15", name: "Kabupaten Sidoarjo", provinceCode: "35" },
  { code: "16", name: "Kabupaten Mojokerto", provinceCode: "35" },
  { code: "17", name: "Kabupaten Jombang", provinceCode: "35" },
  { code: "18", name: "Kabupaten Nganjuk", provinceCode: "35" },
  { code: "19", name: "Kabupaten Madiun", provinceCode: "35" },
  { code: "20", name: "Kabupaten Magetan", provinceCode: "35" },
  { code: "21", name: "Kabupaten Ngawi", provinceCode: "35" },
  { code: "22", name: "Kabupaten Bojonegoro", provinceCode: "35" },
  { code: "23", name: "Kabupaten Tuban", provinceCode: "35" },
  { code: "24", name: "Kabupaten Lamongan", provinceCode: "35" },
  { code: "25", name: "Kabupaten Gresik", provinceCode: "35" },
  { code: "26", name: "Kabupaten Bangkalan", provinceCode: "35" },
  { code: "27", name: "Kabupaten Sampang", provinceCode: "35" },
  { code: "28", name: "Kabupaten Pamekasan", provinceCode: "35" },
  { code: "29", name: "Kabupaten Sumenep", provinceCode: "35" },
  { code: "71", name: "Kota Kediri", provinceCode: "35" },
  { code: "72", name: "Kota Blitar", provinceCode: "35" },
  { code: "73", name: "Kota Malang", provinceCode: "35" },
  { code: "74", name: "Kota Probolinggo", provinceCode: "35" },
  { code: "75", name: "Kota Pasuruan", provinceCode: "35" },
  { code: "76", name: "Kota Mojokerto", provinceCode: "35" },
  { code: "77", name: "Kota Madiun", provinceCode: "35" },
  { code: "78", name: "Kota Surabaya", provinceCode: "35" },
  { code: "79", name: "Kota Batu", provinceCode: "35" },

  // ===== BANTEN (36) =====
  { code: "01", name: "Kabupaten Pandeglang", provinceCode: "36" },
  { code: "02", name: "Kabupaten Lebak", provinceCode: "36" },
  { code: "03", name: "Kabupaten Tangerang", provinceCode: "36" },
  { code: "04", name: "Kabupaten Serang", provinceCode: "36" },
  { code: "71", name: "Kota Tangerang", provinceCode: "36" },
  { code: "72", name: "Kota Cilegon", provinceCode: "36" },
  { code: "73", name: "Kota Serang", provinceCode: "36" },
  { code: "74", name: "Kota Tangerang Selatan", provinceCode: "36" },

  // ===== BALI (51) =====
  { code: "01", name: "Kabupaten Jembrana", provinceCode: "51" },
  { code: "02", name: "Kabupaten Tabanan", provinceCode: "51" },
  { code: "03", name: "Kabupaten Badung", provinceCode: "51" },
  { code: "04", name: "Kabupaten Gianyar", provinceCode: "51" },
  { code: "05", name: "Kabupaten Klungkung", provinceCode: "51" },
  { code: "06", name: "Kabupaten Bangli", provinceCode: "51" },
  { code: "07", name: "Kabupaten Karangasem", provinceCode: "51" },
  { code: "08", name: "Kabupaten Buleleng", provinceCode: "51" },
  { code: "71", name: "Kota Denpasar", provinceCode: "51" },

  // ===== NUSA TENGGARA BARAT (52) =====
  { code: "01", name: "Kabupaten Lombok Barat", provinceCode: "52" },
  { code: "02", name: "Kabupaten Lombok Tengah", provinceCode: "52" },
  { code: "03", name: "Kabupaten Lombok Timur", provinceCode: "52" },
  { code: "04", name: "Kabupaten Sumbawa", provinceCode: "52" },
  { code: "05", name: "Kabupaten Dompu", provinceCode: "52" },
  { code: "06", name: "Kabupaten Bima", provinceCode: "52" },
  { code: "07", name: "Kabupaten Sumbawa Barat", provinceCode: "52" },
  { code: "08", name: "Kabupaten Lombok Utara", provinceCode: "52" },
  { code: "71", name: "Kota Mataram", provinceCode: "52" },
  { code: "72", name: "Kota Bima", provinceCode: "52" },

  // ===== NUSA TENGGARA TIMUR (53) =====
  { code: "01", name: "Kabupaten Kupang", provinceCode: "53" },
  { code: "02", name: "Kabupaten Timor Tengah Selatan", provinceCode: "53" },
  { code: "03", name: "Kabupaten Timor Tengah Utara", provinceCode: "53" },
  { code: "04", name: "Kabupaten Belu", provinceCode: "53" },
  { code: "05", name: "Kabupaten Alor", provinceCode: "53" },
  { code: "06", name: "Kabupaten Flores Timur", provinceCode: "53" },
  { code: "07", name: "Kabupaten Sikka", provinceCode: "53" },
  { code: "08", name: "Kabupaten Ende", provinceCode: "53" },
  { code: "09", name: "Kabupaten Ngada", provinceCode: "53" },
  { code: "10", name: "Kabupaten Manggarai", provinceCode: "53" },
  { code: "11", name: "Kabupaten Sumba Timur", provinceCode: "53" },
  { code: "12", name: "Kabupaten Sumba Barat", provinceCode: "53" },
  { code: "13", name: "Kabupaten Lembata", provinceCode: "53" },
  { code: "14", name: "Kabupaten Rote Ndao", provinceCode: "53" },
  { code: "15", name: "Kabupaten Manggarai Barat", provinceCode: "53" },
  { code: "16", name: "Kabupaten Nagekeo", provinceCode: "53" },
  { code: "17", name: "Kabupaten Sumba Tengah", provinceCode: "53" },
  { code: "18", name: "Kabupaten Sumba Barat Daya", provinceCode: "53" },
  { code: "19", name: "Kabupaten Manggarai Timur", provinceCode: "53" },
  { code: "20", name: "Kabupaten Sabu Raijua", provinceCode: "53" },
  { code: "21", name: "Kabupaten Malaka", provinceCode: "53" },
  { code: "71", name: "Kota Kupang", provinceCode: "53" },

  // ===== KALIMANTAN BARAT (61) =====
  { code: "01", name: "Kabupaten Sambas", provinceCode: "61" },
  { code: "02", name: "Kabupaten Mempawah", provinceCode: "61" },
  { code: "03", name: "Kabupaten Sanggau", provinceCode: "61" },
  { code: "04", name: "Kabupaten Ketapang", provinceCode: "61" },
  { code: "05", name: "Kabupaten Sintang", provinceCode: "61" },
  { code: "06", name: "Kabupaten Kapuas Hulu", provinceCode: "61" },
  { code: "07", name: "Kabupaten Bengkayang", provinceCode: "61" },
  { code: "08", name: "Kabupaten Landak", provinceCode: "61" },
  { code: "09", name: "Kabupaten Sekadau", provinceCode: "61" },
  { code: "10", name: "Kabupaten Melawi", provinceCode: "61" },
  { code: "11", name: "Kabupaten Kayong Utara", provinceCode: "61" },
  { code: "12", name: "Kabupaten Kubu Raya", provinceCode: "61" },
  { code: "71", name: "Kota Pontianak", provinceCode: "61" },
  { code: "72", name: "Kota Singkawang", provinceCode: "61" },

  // ===== KALIMANTAN TENGAH (62) =====
  { code: "01", name: "Kabupaten Kotawaringin Barat", provinceCode: "62" },
  { code: "02", name: "Kabupaten Kotawaringin Timur", provinceCode: "62" },
  { code: "03", name: "Kabupaten Kapuas", provinceCode: "62" },
  { code: "04", name: "Kabupaten Barito Selatan", provinceCode: "62" },
  { code: "05", name: "Kabupaten Barito Utara", provinceCode: "62" },
  { code: "06", name: "Kabupaten Katingan", provinceCode: "62" },
  { code: "07", name: "Kabupaten Seruyan", provinceCode: "62" },
  { code: "08", name: "Kabupaten Sukamara", provinceCode: "62" },
  { code: "09", name: "Kabupaten Lamandau", provinceCode: "62" },
  { code: "10", name: "Kabupaten Gunung Mas", provinceCode: "62" },
  { code: "11", name: "Kabupaten Pulang Pisau", provinceCode: "62" },
  { code: "12", name: "Kabupaten Murung Raya", provinceCode: "62" },
  { code: "13", name: "Kabupaten Barito Timur", provinceCode: "62" },
  { code: "71", name: "Kota Palangkaraya", provinceCode: "62" },

  // ===== KALIMANTAN SELATAN (63) =====
  { code: "01", name: "Kabupaten Tanah Laut", provinceCode: "63" },
  { code: "02", name: "Kabupaten Kotabaru", provinceCode: "63" },
  { code: "03", name: "Kabupaten Banjar", provinceCode: "63" },
  { code: "04", name: "Kabupaten Barito Kuala", provinceCode: "63" },
  { code: "05", name: "Kabupaten Tapin", provinceCode: "63" },
  { code: "06", name: "Kabupaten Hulu Sungai Selatan", provinceCode: "63" },
  { code: "07", name: "Kabupaten Hulu Sungai Tengah", provinceCode: "63" },
  { code: "08", name: "Kabupaten Hulu Sungai Utara", provinceCode: "63" },
  { code: "09", name: "Kabupaten Tabalong", provinceCode: "63" },
  { code: "10", name: "Kabupaten Tanah Bumbu", provinceCode: "63" },
  { code: "11", name: "Kabupaten Balangan", provinceCode: "63" },
  { code: "71", name: "Kota Banjarmasin", provinceCode: "63" },
  { code: "72", name: "Kota Banjarbaru", provinceCode: "63" },

  // ===== KALIMANTAN TIMUR (64) =====
  { code: "01", name: "Kabupaten Paser", provinceCode: "64" },
  { code: "02", name: "Kabupaten Kutai Kartanegara", provinceCode: "64" },
  { code: "03", name: "Kabupaten Berau", provinceCode: "64" },
  { code: "07", name: "Kabupaten Kutai Barat", provinceCode: "64" },
  { code: "08", name: "Kabupaten Kutai Timur", provinceCode: "64" },
  { code: "09", name: "Kabupaten Penajam Paser Utara", provinceCode: "64" },
  { code: "11", name: "Kabupaten Mahakam Ulu", provinceCode: "64" },
  { code: "71", name: "Kota Balikpapan", provinceCode: "64" },
  { code: "72", name: "Kota Samarinda", provinceCode: "64" },
  { code: "74", name: "Kota Bontang", provinceCode: "64" },

  // ===== KALIMANTAN UTARA (65) =====
  { code: "01", name: "Kabupaten Bulungan", provinceCode: "65" },
  { code: "02", name: "Kabupaten Malinau", provinceCode: "65" },
  { code: "03", name: "Kabupaten Nunukan", provinceCode: "65" },
  { code: "04", name: "Kabupaten Tana Tidung", provinceCode: "65" },
  { code: "71", name: "Kota Tarakan", provinceCode: "65" },

  // ===== SULAWESI UTARA (71) =====
  { code: "01", name: "Kabupaten Bolaang Mongondow", provinceCode: "71" },
  { code: "02", name: "Kabupaten Minahasa", provinceCode: "71" },
  { code: "03", name: "Kabupaten Kepulauan Sangihe", provinceCode: "71" },
  { code: "04", name: "Kabupaten Kepulauan Talaud", provinceCode: "71" },
  { code: "05", name: "Kabupaten Minahasa Selatan", provinceCode: "71" },
  { code: "06", name: "Kabupaten Minahasa Utara", provinceCode: "71" },
  { code: "07", name: "Kabupaten Minahasa Tenggara", provinceCode: "71" },
  { code: "08", name: "Kabupaten Bolaang Mongondow Utara", provinceCode: "71" },
  { code: "09", name: "Kabupaten Kepulauan Siau Tagulandang Biaro", provinceCode: "71" },
  { code: "10", name: "Kabupaten Bolaang Mongondow Timur", provinceCode: "71" },
  { code: "11", name: "Kabupaten Bolaang Mongondow Selatan", provinceCode: "71" },
  { code: "71", name: "Kota Manado", provinceCode: "71" },
  { code: "72", name: "Kota Bitung", provinceCode: "71" },
  { code: "73", name: "Kota Tomohon", provinceCode: "71" },
  { code: "74", name: "Kota Kotamobagu", provinceCode: "71" },

  // ===== SULAWESI TENGAH (72) =====
  { code: "01", name: "Kabupaten Banggai", provinceCode: "72" },
  { code: "02", name: "Kabupaten Poso", provinceCode: "72" },
  { code: "03", name: "Kabupaten Donggala", provinceCode: "72" },
  { code: "04", name: "Kabupaten Toli-Toli", provinceCode: "72" },
  { code: "05", name: "Kabupaten Buol", provinceCode: "72" },
  { code: "06", name: "Kabupaten Morowali", provinceCode: "72" },
  { code: "07", name: "Kabupaten Banggai Kepulauan", provinceCode: "72" },
  { code: "08", name: "Kabupaten Parigi Moutong", provinceCode: "72" },
  { code: "09", name: "Kabupaten Tojo Una Una", provinceCode: "72" },
  { code: "10", name: "Kabupaten Sigi", provinceCode: "72" },
  { code: "11", name: "Kabupaten Banggai Laut", provinceCode: "72" },
  { code: "12", name: "Kabupaten Morowali Utara", provinceCode: "72" },
  { code: "71", name: "Kota Palu", provinceCode: "72" },

  // ===== SULAWESI SELATAN (73) =====
  { code: "01", name: "Kabupaten Kepulauan Selayar", provinceCode: "73" },
  { code: "02", name: "Kabupaten Bulukumba", provinceCode: "73" },
  { code: "03", name: "Kabupaten Bantaeng", provinceCode: "73" },
  { code: "04", name: "Kabupaten Jeneponto", provinceCode: "73" },
  { code: "05", name: "Kabupaten Takalar", provinceCode: "73" },
  { code: "06", name: "Kabupaten Gowa", provinceCode: "73" },
  { code: "07", name: "Kabupaten Sinjai", provinceCode: "73" },
  { code: "08", name: "Kabupaten Bone", provinceCode: "73" },
  { code: "09", name: "Kabupaten Maros", provinceCode: "73" },
  { code: "10", name: "Kabupaten Pangkajene dan Kepulauan", provinceCode: "73" },
  { code: "11", name: "Kabupaten Barru", provinceCode: "73" },
  { code: "12", name: "Kabupaten Soppeng", provinceCode: "73" },
  { code: "13", name: "Kabupaten Wajo", provinceCode: "73" },
  { code: "14", name: "Kabupaten Sidenreng Rappang", provinceCode: "73" },
  { code: "15", name: "Kabupaten Pinrang", provinceCode: "73" },
  { code: "16", name: "Kabupaten Enrekang", provinceCode: "73" },
  { code: "17", name: "Kabupaten Luwu", provinceCode: "73" },
  { code: "18", name: "Kabupaten Tana Toraja", provinceCode: "73" },
  { code: "22", name: "Kabupaten Luwu Utara", provinceCode: "73" },
  { code: "24", name: "Kabupaten Luwu Timur", provinceCode: "73" },
  { code: "26", name: "Kabupaten Toraja Utara", provinceCode: "73" },
  { code: "71", name: "Kota Makassar", provinceCode: "73" },
  { code: "72", name: "Kota Parepare", provinceCode: "73" },
  { code: "73", name: "Kota Palopo", provinceCode: "73" },

  // ===== SULAWESI TENGGARA (74) =====
  { code: "01", name: "Kabupaten Kolaka", provinceCode: "74" },
  { code: "02", name: "Kabupaten Konawe", provinceCode: "74" },
  { code: "03", name: "Kabupaten Muna", provinceCode: "74" },
  { code: "04", name: "Kabupaten Buton", provinceCode: "74" },
  { code: "05", name: "Kabupaten Konawe Selatan", provinceCode: "74" },
  { code: "06", name: "Kabupaten Bombana", provinceCode: "74" },
  { code: "07", name: "Kabupaten Wakatobi", provinceCode: "74" },
  { code: "08", name: "Kabupaten Kolaka Utara", provinceCode: "74" },
  { code: "09", name: "Kabupaten Konawe Utara", provinceCode: "74" },
  { code: "10", name: "Kabupaten Buton Utara", provinceCode: "74" },
  { code: "11", name: "Kabupaten Kolaka Timur", provinceCode: "74" },
  { code: "12", name: "Kabupaten Konawe Kepulauan", provinceCode: "74" },
  { code: "13", name: "Kabupaten Muna Barat", provinceCode: "74" },
  { code: "14", name: "Kabupaten Buton Tengah", provinceCode: "74" },
  { code: "15", name: "Kabupaten Buton Selatan", provinceCode: "74" },
  { code: "71", name: "Kota Kendari", provinceCode: "74" },
  { code: "72", name: "Kota Bau Bau", provinceCode: "74" },

  // ===== GORONTALO (75) =====
  { code: "01", name: "Kabupaten Gorontalo", provinceCode: "75" },
  { code: "02", name: "Kabupaten Boalemo", provinceCode: "75" },
  { code: "03", name: "Kabupaten Bone Bolango", provinceCode: "75" },
  { code: "04", name: "Kabupaten Pohuwato", provinceCode: "75" },
  { code: "05", name: "Kabupaten Gorontalo Utara", provinceCode: "75" },
  { code: "71", name: "Kota Gorontalo", provinceCode: "75" },

  // ===== SULAWESI BARAT (76) =====
  { code: "01", name: "Kabupaten Pasangkayu", provinceCode: "76" },
  { code: "02", name: "Kabupaten Mamuju", provinceCode: "76" },
  { code: "03", name: "Kabupaten Mamasa", provinceCode: "76" },
  { code: "04", name: "Kabupaten Polewali Mandar", provinceCode: "76" },
  { code: "05", name: "Kabupaten Majene", provinceCode: "76" },
  { code: "06", name: "Kabupaten Mamuju Tengah", provinceCode: "76" },

  // ===== MALUKU (81) =====
  { code: "01", name: "Kabupaten Maluku Tengah", provinceCode: "81" },
  { code: "02", name: "Kabupaten Maluku Tenggara", provinceCode: "81" },
  { code: "03", name: "Kabupaten Kepulauan Tanimbar", provinceCode: "81" },
  { code: "04", name: "Kabupaten Buru", provinceCode: "81" },
  { code: "05", name: "Kabupaten Seram Bagian Timur", provinceCode: "81" },
  { code: "06", name: "Kabupaten Seram Bagian Barat", provinceCode: "81" },
  { code: "07", name: "Kabupaten Kepulauan Aru", provinceCode: "81" },
  { code: "08", name: "Kabupaten Maluku Barat Daya", provinceCode: "81" },
  { code: "09", name: "Kabupaten Buru Selatan", provinceCode: "81" },
  { code: "71", name: "Kota Ambon", provinceCode: "81" },
  { code: "72", name: "Kota Tual", provinceCode: "81" },

  // ===== MALUKU UTARA (82) =====
  { code: "01", name: "Kabupaten Halmahera Barat", provinceCode: "82" },
  { code: "02", name: "Kabupaten Halmahera Tengah", provinceCode: "82" },
  { code: "03", name: "Kabupaten Halmahera Utara", provinceCode: "82" },
  { code: "04", name: "Kabupaten Halmahera Selatan", provinceCode: "82" },
  { code: "05", name: "Kabupaten Kepulauan Sula", provinceCode: "82" },
  { code: "06", name: "Kabupaten Halmahera Timur", provinceCode: "82" },
  { code: "07", name: "Kabupaten Pulau Morotai", provinceCode: "82" },
  { code: "08", name: "Kabupaten Pulau Taliabu", provinceCode: "82" },
  { code: "71", name: "Kota Ternate", provinceCode: "82" },
  { code: "72", name: "Kota Tidore Kepulauan", provinceCode: "82" },

  // ===== PAPUA (91) =====
  { code: "03", name: "Kabupaten Jayapura", provinceCode: "91" },
  { code: "05", name: "Kabupaten Kepulauan Yapen", provinceCode: "91" },
  { code: "06", name: "Kabupaten Biak Numfor", provinceCode: "91" },
  { code: "10", name: "Kabupaten Sarmi", provinceCode: "91" },
  { code: "11", name: "Kabupaten Keerom", provinceCode: "91" },
  { code: "15", name: "Kabupaten Waropen", provinceCode: "91" },
  { code: "19", name: "Kabupaten Supiori", provinceCode: "91" },
  { code: "20", name: "Kabupaten Mamberamo Raya", provinceCode: "91" },
  { code: "71", name: "Kota Jayapura", provinceCode: "91" },

  // ===== PAPUA BARAT (92) =====
  { code: "02", name: "Kabupaten Manokwari", provinceCode: "92" },
  { code: "03", name: "Kabupaten Fak Fak", provinceCode: "92" },
  { code: "06", name: "Kabupaten Teluk Bintuni", provinceCode: "92" },
  { code: "07", name: "Kabupaten Teluk Wondama", provinceCode: "92" },
  { code: "08", name: "Kabupaten Kaimana", provinceCode: "92" },
  { code: "11", name: "Kabupaten Manokwari Selatan", provinceCode: "92" },
  { code: "12", name: "Kabupaten Pegunungan Arfak", provinceCode: "92" },

  // ===== PAPUA SELATAN (93) =====
  { code: "01", name: "Kabupaten Merauke", provinceCode: "93" },
  { code: "02", name: "Kabupaten Boven Digoel", provinceCode: "93" },
  { code: "03", name: "Kabupaten Mappi", provinceCode: "93" },
  { code: "04", name: "Kabupaten Asmat", provinceCode: "93" },

  // ===== PAPUA TENGAH (94) =====
  { code: "01", name: "Kabupaten Nabire", provinceCode: "94" },
  { code: "02", name: "Kabupaten Puncak Jaya", provinceCode: "94" },
  { code: "03", name: "Kabupaten Paniai", provinceCode: "94" },
  { code: "04", name: "Kabupaten Mimika", provinceCode: "94" },
  { code: "05", name: "Kabupaten Puncak", provinceCode: "94" },
  { code: "06", name: "Kabupaten Dogiyai", provinceCode: "94" },
  { code: "07", name: "Kabupaten Intan Jaya", provinceCode: "94" },
  { code: "08", name: "Kabupaten Deiyai", provinceCode: "94" },

  // ===== PAPUA PEGUNUNGAN (95) =====
  { code: "01", name: "Kabupaten Jayawijaya", provinceCode: "95" },
  { code: "02", name: "Kabupaten Pegunungan Bintang", provinceCode: "95" },
  { code: "03", name: "Kabupaten Yahukimo", provinceCode: "95" },
  { code: "04", name: "Kabupaten Tolikara", provinceCode: "95" },
  { code: "05", name: "Kabupaten Mamberamo Tengah", provinceCode: "95" },
  { code: "06", name: "Kabupaten Yalimo", provinceCode: "95" },
  { code: "07", name: "Kabupaten Lanny Jaya", provinceCode: "95" },
  { code: "08", name: "Kabupaten Nduga", provinceCode: "95" },

  // ===== PAPUA BARAT DAYA (96) =====
  { code: "01", name: "Kabupaten Sorong", provinceCode: "96" },
  { code: "02", name: "Kabupaten Sorong Selatan", provinceCode: "96" },
  { code: "03", name: "Kabupaten Raja Ampat", provinceCode: "96" },
  { code: "04", name: "Kabupaten Tambrauw", provinceCode: "96" },
  { code: "05", name: "Kabupaten Maybrat", provinceCode: "96" },
  { code: "71", name: "Kota Sorong", provinceCode: "96" },
];

export function getProvinceName(code: string): string | null {
  const province = provinces.find(p => p.code === code);
  return province ? province.name : null;
}

export function getCityName(provinceCode: string, cityCode: string): string | null {
  const city = cities.find(c => c.provinceCode === provinceCode && c.code === cityCode);
  return city ? city.name : null;
}

export function isValidProvinceCode(code: string): boolean {
  return provinces.some(p => p.code === code);
}

export function isValidCityCode(provinceCode: string, cityCode: string): boolean {
  return cities.some(c => c.provinceCode === provinceCode && c.code === cityCode);
}
