// Comprehensive nationality to flag emoji mapping
const nationalityFlagMap: Record<string, string> = {
  // Southeast Asia
  indonesia: '🇮🇩',
  malaysia: '🇲🇾',
  thailand: '🇹🇭',
  vietnam: '🇻🇳',
  filipina: '🇵🇭',
  philippines: '🇵🇭',
  singapura: '🇸🇬',
  singapore: '🇸🇬',
  myanmar: '🇲🇲',
  kamboja: '🇰🇭',
  cambodia: '🇰🇭',
  laos: '🇱🇦',
  'timor leste': '🇹🇱',
  brunei: '🇧🇳',
  // East Asia
  jepang: '🇯🇵',
  japan: '🇯🇵',
  korea: '🇰🇷',
  'korea selatan': '🇰🇷',
  'south korea': '🇰🇷',
  'korea utara': '🇰🇵',
  'north korea': '🇰🇵',
  tiongkok: '🇨🇳',
  china: '🇨🇳',
  taiwan: '🇹🇼',
  // South America
  brasil: '🇧🇷',
  brazil: '🇧🇷',
  argentina: '🇦🇷',
  kolombia: '🇨🇴',
  colombia: '🇨🇴',
  uruguay: '🇺🇾',
  chile: '🇨🇱',
  peru: '🇵🇪',
  paraguay: '🇵🇾',
  ekuador: '🇪🇨',
  ecuador: '🇪🇨',
  venezuela: '🇻🇪',
  bolivia: '🇧🇴',
  // Europe
  inggris: '🏴󠁧󠁢󠁥󠁮󠁧󠁿',
  england: '🏴󠁧󠁢󠁥󠁮󠁧󠁿',
  'united kingdom': '🇬🇧',
  spanyol: '🇪🇸',
  spain: '🇪🇸',
  jerman: '🇩🇪',
  germany: '🇩🇪',
  prancis: '🇫🇷',
  france: '🇫🇷',
  italia: '🇮🇹',
  italy: '🇮🇹',
  portugal: '🇵🇹',
  belanda: '🇳🇱',
  netherlands: '🇳🇱',
  belgia: '🇧🇪',
  belgium: '🇧🇪',
  kroasia: '🇭🇷',
  croatia: '🇭🇷',
  serbia: '🇷🇸',
  polandia: '🇵🇱',
  poland: '🇵🇱',
  swedia: '🇸🇪',
  sweden: '🇸🇪',
  norwegia: '🇳🇴',
  norway: '🇳🇴',
  denmark: '🇩🇰',
  swiss: '🇨🇭',
  switzerland: '🇨🇭',
  austria: '🇦🇹',
  turki: '🇹🇷',
  turkey: '🇹🇷',
  rusia: '🇷🇺',
  russia: '🇷🇺',
  ukraina: '🇺🇦',
  ukraine: '🇺🇦',
  rumania: '🇷🇴',
  romania: '🇷🇴',
  yunani: '🇬🇷',
  greece: '🇬🇷',
  ceko: '🇨🇿',
  'czech republic': '🇨🇿',
  czechia: '🇨🇿',
  hungaria: '🇭🇺',
  hungary: '🇭🇺',
  skotlandia: '🏴󠁧󠁢󠁳󠁣󠁴󠁿',
  scotland: '🏴󠁧󠁢󠁳󠁣󠁴󠁿',
  wales: '🏴󠁧󠁢󠁷󠁬󠁳󠁿',
  irlandia: '🇮🇪',
  ireland: '🇮🇪',
  // Africa
  nigeria: '🇳🇬',
  ghana: '🇬🇭',
  kamerun: '🇨🇲',
  cameroon: '🇨🇲',
  senegal: '🇸🇳',
  'pantai gading': '🇨🇮',
  'ivory coast': '🇨🇮',
  mesir: '🇪🇬',
  egypt: '🇪🇬',
  maroko: '🇲🇦',
  morocco: '🇲🇦',
  algeria: '🇩🇿',
  tunisia: '🇹🇳',
  'afrika selatan': '🇿🇦',
  'south africa': '🇿🇦',
  mali: '🇲🇱',
  // Middle East & Central Asia
  'arab saudi': '🇸🇦',
  'saudi arabia': '🇸🇦',
  qatar: '🇶🇦',
  iran: '🇮🇷',
  irak: '🇮🇶',
  iraq: '🇮🇶',
  uzbekistan: '🇺🇿',
  // North & Central America
  amerika: '🇺🇸',
  'united states': '🇺🇸',
  usa: '🇺🇸',
  meksiko: '🇲🇽',
  mexico: '🇲🇽',
  kanada: '🇨🇦',
  canada: '🇨🇦',
  jamaika: '🇯🇲',
  jamaica: '🇯🇲',
  // Oceania
  australia: '🇦🇺',
  'selandia baru': '🇳🇿',
  'new zealand': '🇳🇿',
  // South Asia
  india: '🇮🇳',
  pakistan: '🇵🇰',
  bangladesh: '🇧🇩',
};

export function getNationalityFlag(nationality: string): string {
  if (!nationality) return '🏳️';
  const key = nationality.toLowerCase().trim();
  
  // Direct match
  if (nationalityFlagMap[key]) return nationalityFlagMap[key];
  
  // Partial match
  for (const [name, flag] of Object.entries(nationalityFlagMap)) {
    if (key.includes(name) || name.includes(key)) return flag;
  }
  
  return '🏳️';
}
